/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_cmd_FFmpegCmd */

#ifndef _Included_com_onzhou_ffmpeg_cmd_FFmpegCmd
#define _Included_com_onzhou_ffmpeg_cmd_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_ffmpeg_cmd_FFmpegCmd
 * Method:    exec
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_onzhou_ffmpeg_cmd_FFmpegCmd_exec
        (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
