/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_hello_HelloFFmpeg */

#ifndef INCLUDE_LAME_ENCODE
#define INCLUDE_LAME_ENCODE
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL encode(JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

JNIEXPORT void JNICALL destroy(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
