/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_live_NativeFrame */

#ifndef INCLUDED_COM_ONZHOU_LIVE_NATIVEFRAME
#define INCLUDED_COM_ONZHOU_LIVE_NATIVEFRAME
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_live_NativeFrame
 * Method:    onPreviewFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL onPreviewFrame(JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
