/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_live_NativeFrame */

#ifndef INCLUDED_COM_ONZHOU_LIVE_NATIVEFRAME
#define INCLUDED_COM_ONZHOU_LIVE_NATIVEFRAME
#ifdef __cplusplus
extern "C" {
#endif

#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavutil/avutil.h>
#include <libswscale/swscale.h>

/*
 * Class:     com_onzhou_live_NativeFrame
 * Method:    onPreviewFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL onPreviewFrame(JNIEnv *, jobject, jbyteArray, jint, jint);

JNIEXPORT void JNICALL startPublish(JNIEnv *, jobject, jstring, jint, jint);

JNIEXPORT void JNICALL stopPublish(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
