/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_live_NativeFrame */

#ifndef NATIVE_DECODE_H
#define NATIVE_DECODE_H
#ifdef __cplusplus
extern "C" {
#endif

#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libswscale/swscale.h"
#include "libavutil/log.h"

JNIEXPORT void JNICALL decodeMP4(JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
