/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_NowStreamer */

#ifndef _Included_com_onzhou_ffmpeg_NowStreamer
#define _Included_com_onzhou_ffmpeg_NowStreamer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_ffmpeg_NowStreamer
 * Method:    getAvFormatInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_ffmpeg_NowStreamer_getAvFormatInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

