/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_byhook_ffmpegwithx264_FFmpegPlayer */

#ifndef _Included_cn_byhook_ffmpegwithx264_FFmpegPlayer
#define _Included_cn_byhook_ffmpegwithx264_FFmpegPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_byhook_ffmpegwithx264_FFmpegPlayer
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_byhook_ffmpegwithx264_FFmpegPlayer_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
