/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_streamer_NowStreamer */

#ifndef _Included_com_onzhou_ffmpeg_streamer_NowStreamer
#define _Included_com_onzhou_ffmpeg_streamer_NowStreamer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_ffmpeg_streamer_NowStreamer
 * Method:    startPublish
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_onzhou_ffmpeg_streamer_NowStreamer_startPublish
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
