/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_hello_HelloFFmpeg */

#ifndef INCLUDE_NATIVE_AUDIO
#define INCLUDE_NATIVE_AUDIO
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL startRecord(JNIEnv *, jobject, jint, jint, jint, jstring);

JNIEXPORT void JNICALL stopRecord(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
