/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_ffmpeg_hello_HelloFFmpeg */

#ifndef _Included_com_onzhou_ffmpeg_hello_HelloFFmpeg
#define _Included_com_onzhou_ffmpeg_hello_HelloFFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_ffmpeg_hello_HelloFFmpeg
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_onzhou_ffmpeg_play_FFmpegPlay_playVideo
        (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
