/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_cmake_hello_CmakeHello */

#ifndef _Included_com_onzhou_cmake_hello_CmakeHello
#define _Included_com_onzhou_cmake_hello_CmakeHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_cmake_hello_CmakeHello
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_cmake_hello_CmakeHello_urlprotocolinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_onzhou_cmake_hello_CmakeHello
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_cmake_hello_CmakeHello_avformatinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_onzhou_cmake_hello_CmakeHello
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_cmake_hello_CmakeHello_avcodecinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_onzhou_cmake_hello_CmakeHello
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_cmake_hello_CmakeHello_avfilterinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_onzhou_cmake_hello_CmakeHello
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_onzhou_cmake_hello_CmakeHello_configurationinfo
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
