/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef MP4_STREAM_H
#define MP4_STREAM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavfilter/avfilter.h"
#include "libavutil/mathematics.h"
#include "libavutil/log.h"
#include "libavutil/time.h"

int start_publish(const char *mp4Path, const char *stream);

void stop_publish();

#ifdef __cplusplus
}
#endif


#endif
